import { Platform } from 'react-native';

export const TAB_BAR_HEIGHT = Platform.OS === 'ios' ? 56 : 70;

export const COLORS = {
  light: {
    background: '#F5F9F7',
    text: '#1A3F3C',
    textMuted: '#5E7A75',
    brand: '#1A4A46',
    card: '#FFFFFF',
    cardMuted: '#E8F0ED',
    cardText: '#1A3F3C',
    cardTextMuted: '#6A827E',
    mint: '#7EC8BD',
    mintSoft: '#DCEFEA',
    teal: '#2A5F5A',
    tealDeep: '#214E4A',
    danger: '#C45C6A',
    dangerSoft: '#F7DCE0',
    chart: '#4E6A66',
    chartSoft: '#DCE6E3',
    tabBar: '#FFFFFF',
    tabActive: '#D4EFE8',
    tabInactive: '#8AA19C',
    tabActiveText: '#1F4A46',
    statusBar: 'dark-content',
    headerIcon: '#1A3F3C',
    notificationDot: '#C45C6A',
    badgePendingBg: '#DCEFEA',
    badgePendingText: '#1F4A46',
    badgeDoneBg: '#E1E6E4',
    badgeDoneText: '#6B716F',
    badgeSoonBg: '#2A5F5A',
    badgeSoonText: '#FFFFFF',
    quickPrimaryBg: '#2A5F5A',
    quickPrimaryText: '#FFFFFF',
    quickSecondaryBg: '#FFFFFF',
    quickSecondaryText: '#1A3F3C',
    avatarFallback: '#DCEFEA',
    shadow: '#1A3F3C',
    decor: '#7EC8BD',
    tagline: '#3F5F5A',
    divider: '#2A5F5A',
    skip: '#6A827E',
    iconBg: '#DCEFEA',
    icon: '#2A5F5A',
    dot: '#C9DDD8',
    dotActive: '#2A5F5A',
    buttonBg: '#2A5F5A',
    buttonText: '#FFFFFF',
    version: '#6A827E',
    title: '#1A3F3C',
    body: '#5E7A75',
    fab: '#2A5F5A',
    fabIcon: '#FFFFFF',
    selectedBg: '#2A5F5A',
    selectedText: '#FFFFFF',
  },
  dark: {
    background: '#3E6F69',
    text: '#F5FBFA',
    textMuted: '#D4E6E1',
    brand: '#E9F6F2',
    card: '#EDF5F2',
    cardMuted: '#D7E6E1',
    cardText: '#1F4A46',
    cardTextMuted: '#5A7672',
    mint: '#9FD9CF',
    mintSoft: '#D9EFEA',
    teal: '#2F635D',
    tealDeep: '#275550',
    danger: '#E09198',
    dangerSoft: '#F3D6D9',
    chart: '#4A6A66',
    chartSoft: '#D5E2DE',
    tabBar: '#EDF5F2',
    tabActive: '#C9E9E1',
    tabInactive: '#7A9691',
    tabActiveText: '#1F4A46',
    statusBar: 'light-content',
    headerIcon: '#F5FBFA',
    notificationDot: '#E09198',
    badgePendingBg: '#D4EFE8',
    badgePendingText: '#1F4A46',
    badgeDoneBg: '#D9E0DD',
    badgeDoneText: '#6B716F',
    badgeSoonBg: '#2F635D',
    badgeSoonText: '#F5FBFA',
    quickPrimaryBg: '#2F635D',
    quickPrimaryText: '#FFFFFF',
    quickSecondaryBg: '#EDF5F2',
    quickSecondaryText: '#1F4A46',
    avatarFallback: '#4E827B',
    shadow: '#1A3A36',
    decor: '#7FB5AD',
    tagline: '#D9EBE6',
    divider: '#9FD9CF',
    skip: '#D4E6E1',
    iconBg: '#4E827B',
    icon: '#E9F6F2',
    dot: '#6A938C',
    dotActive: '#9FD9CF',
    buttonBg: '#2F635D',
    buttonText: '#F5FBFA',
    version: '#D4E6E1',
    title: '#F5FBFA',
    body: '#D9EBE6',
    fab: '#2F635D',
    fabIcon: '#FFFFFF',
    selectedBg: '#2F635D',
    selectedText: '#FFFFFF',
  },
};

export const getTabBarTotalHeight = bottomInset =>
  TAB_BAR_HEIGHT + Math.max(bottomInset, Platform.OS === 'ios' ? 6 : 10);
