export const SESSION_TYPES = [
  { id: 't1', name: 'Bireysel Terapi' },
  { id: 't2', name: 'Çift Terapisi' },
  { id: 't3', name: 'Aile Danışmanlığı' },
];

export const CLIENTS = [
  {
    id: 'c1',
    name: 'Ayşe Yılmaz',
    initials: 'AY',
    type: 'Bireysel Terapi',
    phone: '0532 111 22 33',
    accent: 'mint',
  },
  {
    id: 'c2',
    name: 'Mehmet Çelik',
    initials: 'MÇ',
    type: 'Çift Terapisi',
    phone: '0533 444 55 66',
    accent: 'teal',
  },
  {
    id: 'c3',
    name: 'Zeynep Kaya',
    initials: 'ZK',
    type: 'Bireysel Terapi',
    phone: '0541 777 88 99',
    accent: 'teal',
  },
  {
    id: 'c4',
    name: 'Can Demir',
    initials: 'CD',
    type: 'Aile Danışmanlığı',
    phone: '0505 123 45 67',
    accent: 'mint',
  },
];

export const SESSIONS = [
  {
    id: 's1',
    clientId: 'c1',
    name: 'Ayşe Yılmaz',
    initials: 'AY',
    type: 'Bireysel Terapi',
    time: '10:00',
    duration: '50 dk',
    status: 'pending',
    notes: 'İlk görüşme notları ve ev ödevi takibi.',
  },
  {
    id: 's2',
    clientId: 'c2',
    name: 'Mehmet Çelik',
    initials: 'MÇ',
    type: 'Çift Terapisi',
    time: '13:30',
    duration: '60 dk',
    status: 'completed',
    notes: 'Seans tamamlandı. İletişim egzersizi verildi.',
  },
  {
    id: 's3',
    clientId: 'c3',
    name: 'Zeynep Kaya',
    initials: 'ZK',
    type: 'Bireysel Terapi',
    time: '15:00',
    duration: '50 dk',
    status: 'upcoming',
    notes: 'Hedef netleştirme ve kaygı çalışması.',
  },
  {
    id: 's4',
    clientId: 'c4',
    name: 'Can Demir',
    initials: 'CD',
    type: 'Aile Danışmanlığı',
    time: '17:30',
    duration: '50 dk',
    status: 'upcoming',
    notes: 'Ebeveyn-çocuk iletişimi üzerine çalışma.',
  },
];

export const HOMEWORK = [
  {
    id: 'h1',
    title: 'Duygu günlüğü',
    clientId: 'c1',
    client: 'Ayşe Yılmaz',
    sessionId: 's1',
    due: new Date().toISOString(),
  },
  {
    id: 'h2',
    title: 'İletişim egzersizi',
    clientId: 'c2',
    client: 'Mehmet Çelik',
    sessionId: 's2',
    due: new Date(Date.now() + 86400000).toISOString(),
  },
  {
    id: 'h3',
    title: 'Nefes çalışması',
    clientId: 'c3',
    client: 'Zeynep Kaya',
    sessionId: 's3',
    due: new Date(Date.now() + 2 * 86400000).toISOString(),
  },
  {
    id: 'h4',
    title: 'Aile sözleşmesi',
    clientId: 'c4',
    client: 'Can Demir',
    sessionId: 's4',
    due: new Date(Date.now() + 3 * 86400000).toISOString(),
  },
];
